fmihpc/analysator

pyCalculations/calculations.py, pyCalculations/themis_observation.py, pyMayaVi/mayavigrid.py
These commits add a new picker to the MayaVi Grid view, where an artificial Themis Spacecraft's EMS detector is put at the selected point.
This creates a single snap-shot image of what the detector would see in the selected spot, plotting it as a polar plot. No further processing of the detector count rates is done based on that, but this data can now be used for exactly themis-like analyses.
=> Artificial Themis Observations

pyCalculations/calculations.py, pyCalculations/themis_observation.py, pyMayaVi/mayavigrid.py
Themis observation plots renamed, enhanced, and added a heli plotstyle.
There's now three pickers for this:
* themis_detector plots a single-snapshot themis detector view, giving
countrates, without interpolating or blurring
* themis_contour gives phasespace plots similar to Lynn's, with dodgy
contours that you can't actually quite read.
* themis_helistyle gives the same data with heli's preferred plotting
style, that actually allows you to see something
Also, for the last two, the plot axes fo the 2d cut can be specified at he plot's parameter filed in mayaviGrid, with values such as "x y" to get phasespace aligned to simulatoin aexs, or "B v" to get the plane spun by magnetic field and bulk velocity in the selected cell.
=> Update to artificial themis observations.

pyMayaVi/mayavigrid.py, pyVlsv/vlsvreader.py
This should be merged in regard to Vlasiator-3.0 work.
=> Picker fix

pyCalculations/calculations.py, pyCalculations/cut3d.py, pyCalculations/cutthrough.py, pyCalculations/intpol_file.py, pyCalculations/intpol_points.py, pyCalculations/themis_observation.py, pyMayaVi/mayavigrid.py, pyVlsv/vlsvreader.py
This branch merges fmihpc/fix_issue22 and ykempf/picker_fix into fmihpc/master. This works for Vlasiator-3.0 files.
Further development (e.g. multipop support) should be done after this is merged.
=> Vlasiator 3 updates

pyVlsv/reduction.py
=> Added 1.0/3.0 to Pressure reducer.

tools/vlsvintpol.py
@galfthan is this correct? I hope I did not bothc your previous change.
But: as discussed, the return in the loop is faulty. I am fixing this shortly.
=> Trivial parallelisation of vlsvintpol using poolmap().

pyPlots/colormaps.py, pyPlots/plot.py, pyPlots/plot_panel.py, pyPlots/plot_vdf.py, pyVlsv/vlsvfile.py, pyVlsv/vlsvparticles.py, pyVlsv/vlsvreader.py
Updated the plot_colormap routine, added plot_vdf routine, added interface to read particle pusher output, added two colormaps.
=> Plotting routines multipop

examples/generate_panel.py, pyPlots/plot_panel.py
Works but not pretty. Cleaned up some documentation.
=> Time averaging for plot_colormap expressions

pyPlots/plot_isosurface.py, pyVlsv/vlsvreader.py
This is the optimisation I came up with today. This allows to pass an array of coordinates to read_interpolated_variable() which are processed using one access to the variable. For the case of plotting a large isosurface with O(30k) vertices which need an iterpolated value for colouring, the speedup is from ~40 min to ~25 s. This is what is now implemented in plot_isosurface.
=> Optimise read interpolated variable

pyPlots/plot_colormap.py, pyPlots/plot_vdf.py
Added extra boldfacing to axis labels to work better with up-to-date versions of matplotlib
=> Plotting boldface

pyPlots/plot_vdf.py
Now names vperp1 and vperp2 correctly as BxV and Bx(BxV)
=> Plot vdf vperp axis names

pyPlots/plot_vdf.py
set keyword contours=N to plot  N logarithmically spaced contours
=> added contour plotting

pyPlots/plot_vdf.py
Does linear interpolation between cell faces for each component. Not a divergence-free method, but good enough for plotting (?).
=> Plot_vdf use cell center magnetic field

pyPlots/plot_colormap.py
Use these for vectors, streamlines, the flux function, and external plotting functions.
=> Calculate centre-of-cell coordinates for the mesh

pyVlsv/vlsvparticles.py, pyVlsv/vlsvreader.py
Fixes a problem where a length cannot be defined for a single numpy variable
=> Pythonize vlsvreader cellid check

pyVlsv/reduction.py
The title says it, open for comments and debugging eyes...
=> Added the reducer for the Poynting vector.

pyPlots/plot_colormap.py
I added a comoving flux fix which works in AFC, **I did NOT test with a polar run**.
I also suggest to use fluxthick for the streamline thickness instead of thick which also controls the axes' thickness.
=> Comoving flux

pyCalculations/cutthrough.py, pyPlots/plot_vdf.py, pyVlsv/vlsvvariables.py
=> Plot_vdf can now center on highest phase space density

pyVlsv/reduction.py
https://agupubs.onlinelibrary.wiley.com/doi/epdf/10.1002/2015GL066980
=> added data reducer for per-population agyrotropy

pyVlsv/reduction.py
Should now in fact work for pressure tensors and the diagonal & off-diagonal as well. @lturc, can you confirm your tests for single-cell reads and arrays are ok, for the different shapes of data products?
=> Added dimension checks to temperature calculation

pyPlots/plot_colormap.py
The reshaping of pass_maps in plot_colormap did not work for tensors, so I fixed that.
It now works fine for plotting colormaps, but I haven't tested the single-cell version.
=> Fix tensor plot colormap

pyPlots/plot.py, pyPlots/plot_vdf_profiles.py
might well have still bugs related to keywords and their availability, but can be used for testing.
=> Implemented first version of tool for plotting profiles across a VDF

pyVlsv/vlsvreader.py
This first rough version only reads a complete field, is not properly tested yet, and is not transparent to the user yet... but at least there's some code for it now. Ideas and comments please!
=> Fsgrid variable reader

pyVlsv/vlsvreader.py
Now, this is a pull request against the correct branch.
It fixes integer division and other datatype nysvät that prevented the fsgrid reader to work with python 3.
=> Fix fsgrid reader function python3 compatibility

pyPlots/plot_helpers.py
https://doi.org/10.3847/1538-4357/aa745e
Equations (3)-(7)
=> Added current density helpers for FTE study

pyVlsv/vlsvreader.py
This caused problems at the periodic edges of isosurface plots I am making.
=> Bugfix in read_interpolated_variable

pyPlots/plot_colormap.py
Current branch of vlasiator electrons can output zero rhom if protons are not propagated. This fix allows plotting even if we have zero mass density everywhere.
=> Plot with zero rho

pyPlots/plot_colormap.py, pyPlots/plot_colormap3dslice.py, pyPlots/plot_helpers.py, pyVlsv/reduction.py
Reworked plot_helper expressions to return vectors so that operator commands can be easily used. Fixed some integer warnings cropping up in python 3.
=> More reducers

pyPlots/plot_colormap.py, pyPlots/plot_helpers.py
Includes a variable remapper in plot_colormap to translate expression variable to Vlasiator 5 variable (fg_, etc); only re-mapping B to vg_b_vol so far.
I still get some runtime errors from div-by-zero from *guarded* divisions, not sure why (e.g. from plot_helpers:490), but looks okay.
Whitespace edits thanks to atom.
=> Expressions for flux-limited J = rot(B) calculation.

pyCalculations/ids3d.py, scripts/magnetopause2d.py, scripts/magnetopause3d.py
Scripts magnetopause2d.py and magnetopause3d.py and a fix to ids3d.py.
Scripts have tools to find and plot magnetopause place by streamlining method.
Fix to ids3d.py is mapping list to int to make 3d data work (magnetopause3d doesn't work without fixing ids3d).
=> Magnetopause scripts and a fix to ids3d

pyVlsv/vlsvreader.py
Several (not yet final) updates to pyVlsv/vlsvreader.py to support the AMR:
- Created function to get the AMR maximum refinement level: get_max_refinement_level()
- Created function to get the refinement level of a given cell: get_amr_level(cellid)
- Modified get_cellid() to support AMR
- Modified get_cell_coordinates() to support AMR
- Modified get_cell_indices() to support AMR
- DISCLAIMER: get_cell_neighbor() is still work-in-progress!
=> AMRreading

pyPlots/plot.py, pyPlots/plot_ionosphere.py, pyVlsv/vlsvreader.py
This pull request adds a bunch of support functions here and there to handle ig_ variables.
As the ionosphere data is stored on an unstructured mesh, there is unfortunately no easy way to bring them into any "ordered" format, so they are simply read in-order and the plotting function has to figure out what is where.
A basic plot_ionosphere implementation is also shipped along here, which produces plots like this:
It is still a bit rough around the corners, but I suppose this is a good starting point.
=> Support for ionosphere meshes and plot_ionosphere implementation.

pyCalculations/pitchangle.py, pyCalculations/spectra.py
Supercedes #172 
Updated energy and velocity spectra and pitch angle analysis to work with V5 variables.
Also made improvements to e.g. how differential spectra are normalized
=> Pitch angle update II

pyCalculations/variable.py, pyVlsv/reduction.py
Now on the correct (master) base branch!
=> FHA-style jacobian reducer, incl. vg_J.

pyVlsv/vlsvreader.py
A helper to read XML attributes and a shorthand wrapper for getting the vectorsize.
=> Attribute reading interface and a helper function

pyCalculations/fieldtracer.py
Added static_field_tracer_3d() to fieldtracer.py directly.
This is to get around merge conflicts in https://github.com/fmihpc/analysator/pull/180
=> Updated fieldtracer.py

pyPlots/plot.py, pyPlots/plot_colormap3dslice.py, pyPlots/plot_isosurface.py
Transparency toggle to plot_isosurfaces, tick bug fix in plot_colormap3dslice
Added plot_neutral_sheet to plot_isosurfaces.py, works in a similar fashion to plot_colormap3dslice. Expressions and vectors should be functional
=> Neutral (current) sheet plotter

pyVlsv/vlsvreader.py
Also, adding a limit to varname splitting - multiple slashes in a varname would also break otherwise.
=> Went too deep with the varname fixes, reverting a bit.

pyVlsv/vlsvwriter.py
Not writing anything if data is not found in file or data reducers (and prints errors for it).
=> Write none checks

pyCalculations/fieldtracer.py
Added interpolation for edge-centered variables (such as fg_e) to 3D static field tracer
=> Interpolation for fg_e field tracing 

pyVlsv/vlsvreader.py, pyVlsv/vlsvwriter.py
Enables Multiprocessing for VlsvReader operations by wrapping the fileptr for pickling.
Also includes a vlsvWriter vlsv cloning utility function for Asterix.
=> Pickleable fptr

pyVlsv/vlsvreader.py
blockCoordinates in function, blockcoordinates in function arguments. Guessing no-one has used this function in a while ^^'
=> Fix a 6yo typo

README
Added the documentation link to the README
=> added doc link to readme

tools/grid_from_cellids.py
and base grid dimensions to plot the cells.
Default gives this:
=> Simple matplotlib plotter taking a list of cellids

pyPlots/plot_colormap.py, pyVlsv/vlsvfile.py, pyVlsv/vlsvvtkinterface.py, testpackage/run_testpackage_colormap.sh, testpackage/run_testpackage_vdf.sh, testpackage/testpackage_colormap.py, testpackage/testpackage_vdf.py
Dusting off Markus' testpackage! This made for a couple of bugfixes.
- directories for Turso/Vakka updated
- plot_colormap has fixes to vminuse/vmaxuse detection, need to be propagated elsewhere (or rather, packaged as some separate modular unit).
- better import error handling for the optional VTK features
- gyrotropy reducers updated to corrected ones
This can be further built on now to get a verification set and proper CI.
=> Testpackage redux

pyPlots/plot_helpers.py
I have added three separate plot helpers for each of the three components of the current density (calculated from curl B in 2D runs).
I have tested this only for v5 variable names, but former variable names ('B' for magnetic field) are also included.
=> Added separate plot helpers for the 3 components of current density

analysator/pyCalculations/calculations.py, analysator/pyCalculations/timeevolution.py
AMR support for time series extraction - use `calculations.point_time_evolution` with coordinate instead of cellid.
=> Pointwise time evolution

analysator/pyVlsv/reduction.py
Added:
1. add ionosphere node coordinates
2. mlt output on vg and ig coordinates
3. field line open-closed values check
=> Add mlt check on vg and ig grid, field line oc values

analysator/pyPlots/plot_colormap.py, analysator/pyPlots/plot_colormap3dslice.py
So that the Sun is on the left :)
=> Add option to flip x-axis to plot_colormap and plot_colormap3dslice
