- tools/vlsvintpol.py
I fixed vlsvintpol so that it can also read the times of older simulations like ABA (time used to be called t instead of time)
> Fix reading of time parameter in vlsvintpol

- pyMayaVi/mayavigrid.py
- pyVlsv/reduction.py
Three bugfixes to make point-and-click velocity distribution plotting great again.
- 6c18f69 gives an error message when no vdf is stored in the file at all.
- 29174a1plots the marker of the pick location in the main window instead of the past one. Requires to store the original figure. Also gets rid of the automatic reset of the zoom of the original view.
- 719b266 removes a True threading parameter without apparent problems. This was generating nasty crashes e.g. when trying to change visualisation parameters.
Please some people test this with your favourite work flow before we merge it, hopefully in the next days.
> Bugfixes 20170629

- README
- examples/generate_movie.sh
- pytools.py
Here's a fix to Liisa's and my issues, discussed with @markusbattarbee.
If the environment variable PTINTERACTIVE is set (to anything), then the interactive backend is set and the grid module is loaded. Otherwise the backend is set to Agg and the grid import is skipped.
> Interactive fix

- pyVlsv/vlsvreader.py
Current limitation is that only one coordinate can be converted to an id at a time.
Tested with:
```
import pytools as pt
d = pt.vlsvfile.VlsvReader('../../vlasiator-testi2/bulk.0000054.vlsv') # from magnetospheric test
for c in range(100000):
if d.get_velocity_cell_ids(d.get_velocity_cell_coordinates(c)[0]) != c:
print c, d.get_velocity_cell_ids(d.get_velocity_cell_coordinates(c)[0])
exit('fail')
```
which after about 10 s returned successfully.
> Add a function to get velocity cell id from velocity

- pyCalculations/themis_observation.py
- pyMayaVi/mayavigrid.py
- pyVlsv/vlsvreader.py
This extends the vlsvreader to be able to handle multiple populations in a vlsv file (instead of just going with whatever it finds first).
Basically every population-reading function got an additional "pop" argument, in which the desired population can be specified.
Of course, the higher-level scripts will have to still be adapted to use this.
> Multipop velocity space support in vlsvreader.

- pyVlsv/vlsvreader.py
- tools/vlsvintpol.py
Took me half an hour to identify, and the cause was just a bad usage of the command line options...
If there is an invalid file (or e.g. a list file instead of a list of files passed on the command line) passed, this goes to `except:` but still tries to close `f`, which leads to `UnboundLocalError: local variable 'f' referenced before assignment`.
Better use a variant like the one below.
And it seems that the commit from last November is synonymous to later merges.
> Fix in vlsvintpol

- pyCalculations/calculations.py
- pyCalculations/cutthrough.py
This acts like cut_through, except instead of returning every cell through which the line passes, it finds the dominant cartesian direction, and proceeds to always return the next cell in that dominant direction through which the actual line passes. This should prevent jagged artefacts when plotting diagonal lineouts without having to resort to the dampening done by lineout.
> added cut_through_step for optimized non-jumpy cut-throughs

- pytools.py
This prevents one class of latex errors from temp file clash race
conditions in array jobs.
> Unique matplotlib temp dirs in example array job.

- pyVlsv/vlsvreader.py
This is an enhancement in response to #84 
Instead of doing read loops over data reducers and performing a large number of separate file accesses, the list of cellids is passed on to the lowest-level function. Data reduction calculations (e.g. rotations for parallel and perpendicular values) are only performed for the requested data.
If requesting more than 5000 cellids in one call, the reader reads the whole data instead in one file access and then sifts through it using the built-in vlsvreader cellid dictionary.
> Pass cellids to reducers and improve performance of multi-cellid reads

- pyPlots/plot_vdf.py
In plot_vdf script:
- added caxes argument to provide a set of axes for the colorbar instead of creating one / not displaying it
- changed axis label units from km/s into km s^{-1} and from m/s into m s^{-1}
- prevented colorbar title overlap with tick labels when font size is increased
- removed call to plt.tight_layout() when the plot is made in a set of axes given by the user
> Added caxes argument to plot_vdf for colorbar + minor edits

- examples/multi_panel_plot.py
- pyPlots/plot_colormap.py
- pyPlots/plot_vdf.py
* In pyPlots/plot_colormap.py, added 'axes' and 'cbaxes' parameters to plot_colormap to draw in user-defined set of axes rather than on screen or in a file
* Added an example file using these new features (examples/multi_panel_plot.py)
* In pyPlots/plot_vdf.py, added a 5% margin to slice thickness in the case of double rotation to prevent local undersampling
> Added axes and cbaxes parameters in plot_colormap

- pyPlots/plot_colormap.py
I found a bug with the "lin" keyword in plot_colormap. It was automatically set to True when the symlog option was not used, and as a result setting the number of colorbar ticks with this keyword didn't work anymore.
> Fixed bug with linear colorbar ticks

- pyVlsv/vlsvreader.py
Should make it faster if reading lots and lots of velocity spaces from a single vlsvreader object. Old functionality can be still activated with:
f = pt.vlsvfile.VlsvReader(filename)
f.use_dict_for_blocks = True
> Optimize velspacereads

- scripts/estimate_rerefine.py
Adds script to estimate re-refinement introduced in https://github.com/fmihpc/vlasiator/pull/497
The estimate requires the following datareducers in output:
- vg_amr_alpha
- vg_amr_reflevel
- vg_gridcoordinates
- populations_vg_blocks
You can change the parameters used to match the AMR parameters you wish to use for adapting refinement. The estimate does not currently take into account induced refines: if any cell gets refined two levels higher than its neighborhood (5x5x5) they get refined up to one level below.
> Add script for estimating AMR re-refinement

- pyVlsv/vlsvreader.py
Issue with indexing was cropping up especially in small spatial domains and small task counts. Fixed.
> corrected task indexing in vlsvreader for fsgrids

- pyVlsv/vlsvreader.py
This PR adds support for printing Vlasiator version info and the config file if those are included in bulk or restarts files. Otherwise it lets the user know those were not included in the given files and returns False.
Usage is simple:
`f.print_version()`
> Support for printing vlasiator version and config info from VLSV files

- pyVlsv/vlsvreader.py
This affects, for example, files that only contain an ionosphere mesh, as the ionosphere MiniApp is producing.
> Allow reading vlsv files without a spatialCell or populations.

- pyVlsv/vlsvreader.py
This implements a trilinear interpolation routine for FsGrid data and tries to resolve issue #136 .
Boundaries are handled  the following way:
- If a point is outside of a non periodic domain NaN is returned. My thought proccess here is that maybe we have some SC orbit and that goes out of our domain during some part of it. Then we would not want to discard all the orbit but only part of it. Hence the NaN returned there.
- If a point is outside of a  periodic domain  then the neighbor is only given if the point is one cell away of the periodic dimension. Otherwise a NaN is returned. (here we could fold over the point back into the domain like particles in PIC but not sure what you think)
- If a point is inside the domain but one of its neighbors cannot be located then a NaN is returned. …
> Fs Grid data interpolation

- pyPlots/plot_colormap3dslice.py
Copied the imshow backend for plot_colormap3dslice over from plot_colormap.
> Imshow plot3dslice

- examples/sidecar.py
- pyVlsv/vlsvreader.py
- pyVlsv/vlsvwriter.py
Sidecar postprocessing for analysator, with an example script to calculate J in EGI.
Helpers, fixes from vlsvPostprocessing branch now in a format that does not remove ionosphere additions, for whatever reason. Includes Yann's optimization for fsgrid-SpatialGrid mapping, which is here adapted to be cached for successive calls.
> Vlsv postprocessor2

- pyVlsv/reducer.py
- pyVlsv/reduction.py
- pyVlsv/vlsvreader.py
- pyVlsv/vlsvwriter.py
Fast SpatialGrid coordinate extraction (plus AMR level and dx extraction), accessible also via `read_variable("vg_dxs")` and `read_variable("vg_coordinates")` - needed special handling though, since I want to use these in xo_tools datareducers.
> vlsvReader improvements

- pyVlsv/vlsvwriter.py
So, checking the first element of numpy MaskedArrays for datatypes is not great, as those elements may be `np.ma.core.MaskedConstant`s which break the writer. Instead, fetching the built-in numpy dtype from the array metadata seems a more robust solution...
> Use numpy dtypes of array instead of checking the first element.

- pyVlsv/vlsvwriter.py
Kosta found weird XML entries in vlsv footers. Here's some guards against having incomplete XML elements written to .vlsv files; also more warnings (although not errors) for writing ill-formed data; with the reasoning that in case some pipeline fails, we don't necessarily want to throw away all results from a possibly length script... but could also be errors instead to enforce well-behaved code.
> Write none checks

- pyVlsv/vlsvreader.py
Enforce that user-requested names and meshes must match vlsv footer attributes instead of ignoring them.
> Prevent misleading return of data from vlsvreader when using ill-formed requests

- pyCalculations/variable.py
Suppress the warning printouts. The commented-out ones are not exactly cut-and-dry, since they could indicate missing entries in an existing custom dict, but there was something about the behavior with the default case that had me scratching my head. At least this will be less confusing for now.
> Suppress confusing printouts

- pyCalculations/interpolator_amr.py
- pyVlsv/vlsvreader.py
RBF interpolator not available on old SciPy versions, this guards against that with a fallback and a warning message. Also a bit of cleanup.
> RBFInterpolator guarding

- pyPlots/plot_vdf.py
- pyPlots/plot_vdf_profiles.py
- pyVlsv/vlsvreader.py
- scripts/create_time_energy_spectrogram.py
- trash_can/plot_veldist.py
If nearest_vdf==True, get_cellid() will return the cellid of the nearest cell that contains vdf data.
Tested with visit to check if function gets the right cellids input and output.
Data types (scalar vs. array) are handled, same behavior regardless of whether nearest_vdf==True
> added nearest_vdf keyword to vlsvReader's get_cellid()

- pyPlots/plot.py
- pyPlots/plot_colormap.py
- pyPlots/plot_colormap3dslice.py
- pyPlots/plot_ionosphere.py
- pyPlots/plot_isosurface.py
- pyPlots/plot_threeslice.py
- pytools.py
So, modifiying some latex/mathmode string handling to not complain about deprecated escape sequences. Probably the best practice solution would be to use raw strings consistently here - but that's a chore and a half to go through.
> Deprecated escape

- pytools.py
Quick addition to enable DeprecationWarnings, since https://peps.python.org/pep-0565/ disables them from imported modules. This way we can stay ahead of the curve a bit better...
This also immediately shows that our current method of handling deprecated APIs is going to be deprecated:
```
/home/mjalho/proj/analysator/pyPlots/plot_colormap.py:41: DeprecationWarning: The distutils package is deprecated and slated for removal in Python 3.12. Use setuptools or check PEP 632 for potential alternatives
from distutils.version import LooseVersion, StrictVersion
```
> Enable deprecationwarnings

- pyPlots/plot_vdf.py
Previously, the checks for `cbulk is not None` or the `center` keyword being set to "bulk" or "centre" were sloppy and sometimes warned or errored. Still not pythonesque with try-catches but might work better now?
> Fix plot vdf centering

- pyVlsv/vlsvreader.py
This is a fix for PR #82 :
The problem is that if for any reason the `test_variable` used in `read_interpolated_variable` is masked, `isinstance(test_variable, Iterable)` will return `True` but `value_length=len(test_variable)` will throw the error `TypeError: len() of unsized object`. This is because the masked value is of type `np.ma.core.MaskedConstant`, which inherits the property of `Iterable` from somewhere, but it's actually not iterable.
This PR adds an additional check for `np.ma.core.MaskedConstant` and sets `value_length=1` if the value is masked.
> Added check to catch masked constants in read_interpolated_variable

- pyVlsv/vlsvreader.py
Instead, read in 4kb blocks in a loop until the end of file.
> Don't have a fixed 100kb sizelimit for the xml footer anymore.

- pyVlsv/reduction.py
Adds magnetic pressure data reducer to analysator.
> Add magnetic pressure data reducer

- scripts/gics.py
Updated the geoelectric field calculation in gics.py, to conform with a published reference (Liu et al 2009).
Implemented a method keyword in E_horizontal(), to choose between integrating dB/dt using a right-handed sum or using the more exact Liu et al method. I checked manually that a time series of the geoelectric field vector is almost indistinguishable between the two methods.
> geoelectric field discrete integral

- .github/workflows/sphinx.yml
- Documentation/sphinx/conf.py
- pyVlsv/vlsvreader.py
- scripts/magnetopause2d.py
- scripts/magnetopause3d.py
Sphinx build will now fail on errors and warnings, and will display as an issue on PRs.
> Enforce Sphinx docstring error and warning fixes

- miscellaneous/rankine.py
- pyCalculations/timeevolution.py
- pyMayaVi/particlepusherinterface.py
- scripts/magnetopause2d.py
- scripts/magnetopause3d.py
> Pylab deprecation

- pyVlsv/reduction.py
Vlasiator variable names for B Jacobian components have changed. This introduces an `Alias` function that can be used to define different read targets via reducers for cases when the wanted variable is stored under another name.
> Reducer aliases

- analysator/pyPlots/plot_ionosphere.py
(Concretely, the ionosphere miniApp creates such vlsv files, so this enables plotting those outputs)
> Allow ionosphere plots without a valid time value.

- examples/generate_panel.py
- testpackage/testpackage_colormap.py
Added `out=` parameter to np.add when `where=` as this causes issues with uninitialized arrays:
From https://numpy.org/doc/2.3/reference/generated/numpy.add.html
"Note that if an uninitialized out array is created via the default out=None, locations within it where the condition is False will remain uninitialized."
> Fixing numpy.add 'where' usage in testpackage and examples/generate_panel.py
